version: '3.3'
services:
  app:
    build: .
    container_name: node-app
    ports:
      - 8081:3000
  mongo:
    image: mongo
    container_name: mongo-bd
    ports:
      - 27017:27017
    volumes:
      - mongodb:/app/db
volumes:
  mongodb:
